### ISSUE TITLE
Бот не реагирует, если картинка с заданием в игре недоступна

### ISSUE THREAD

**Issue by gbagretsov** [gbagretsov/friends-vk-bot#147]

**Comment by gbagretsov** [comment]
Пример ошибки:
```
2022-05-16T13:15:20.653674+00:00 app[web.1]: Error: Client network socket disconnected before secure TLS connection was established
2022-05-16T13:15:20.653682+00:00 app[web.1]: at connResetException (internal/errors.js:639:14)
2022-05-16T13:15:20.653682+00:00 app[web.1]: at TLSSocket.onConnectEnd (_tls_wrap.js:1570:19)
2022-05-16T13:15:20.653683+00:00 app[web.1]: at TLSSocket.emit (events.js:412:35)
2022-05-16T13:15:20.653683+00:00 app[web.1]: at endReadableNT (internal/streams/readable.js:1333:12)
2022-05-16T13:15:20.653683+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:82:21) {
2022-05-16T13:15:20.653684+00:00 app[web.1]: code: 'ECONNRESET',
2022-05-16T13:15:20.653684+00:00 app[web.1]: path: null,
2022-05-16T13:15:20.653685+00:00 app[web.1]: host: 'img.gazeta.ru',
2022-05-16T13:15:20.653685+00:00 app[web.1]: port: 443,
2022-05-16T13:15:20.653685+00:00 app[web.1]: localAddress: undefined
2022-05-16T13:15:20.653685+00:00 app[web.1]: }
```
